[2024-06-27 13:46:48 -0400] [1204842] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:2000']
  backlog: 2048
  workers: 4
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/roboticslab/Developer/laimatt/laimatt_pdal
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/roboticslab/Developer/laimatt/laimatt_pdal/gunicorn_logs/gunicorn-access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/roboticslab/Developer/laimatt/laimatt_pdal/gunicorn_logs/gunicorn-error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f7372d47060>
  on_reload: <function OnReload.on_reload at 0x7f7372d471a0>
  when_ready: <function WhenReady.when_ready at 0x7f7372d472e0>
  pre_fork: <function Prefork.pre_fork at 0x7f7372d47420>
  post_fork: <function Postfork.post_fork at 0x7f7372d47560>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f7372d476a0>
  worker_int: <function WorkerInt.worker_int at 0x7f7372d477e0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f7372d47920>
  pre_exec: <function PreExec.pre_exec at 0x7f7372d47a60>
  pre_request: <function PreRequest.pre_request at 0x7f7372d47ba0>
  post_request: <function PostRequest.post_request at 0x7f7372d47c40>
  child_exit: <function ChildExit.child_exit at 0x7f7372d47d80>
  worker_exit: <function WorkerExit.worker_exit at 0x7f7372d47ec0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f7372d64040>
  on_exit: <function OnExit.on_exit at 0x7f7372d64180>
  ssl_context: <function NewSSLContext.ssl_context at 0x7f7372d64360>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  header_map: drop
  tolerate_dangerous_framing: False
[2024-06-27 13:46:48 -0400] [1204842] [INFO] Starting gunicorn 22.0.0
[2024-06-27 13:46:48 -0400] [1204842] [DEBUG] Arbiter booted
[2024-06-27 13:46:48 -0400] [1204842] [INFO] Listening at: http://0.0.0.0:2000 (1204842)
[2024-06-27 13:46:48 -0400] [1204842] [INFO] Using worker: sync
[2024-06-27 13:46:48 -0400] [1204863] [INFO] Booting worker with pid: 1204863
[2024-06-27 13:46:48 -0400] [1204863] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2024-06-27 13:46:48 -0400] [1204863] [INFO] Worker exiting (pid: 1204863)
[2024-06-27 13:46:48 -0400] [1204865] [INFO] Booting worker with pid: 1204865
[2024-06-27 13:46:48 -0400] [1204865] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roboticslab/Developer/laimatt/laimatt_pdal/.conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2024-06-27 13:46:48 -0400] [1204865] [INFO] Worker exiting (pid: 1204865)
[2024-06-27 13:46:48 -0400] [1204842] [ERROR] Worker (pid:1204863) exited with code 3
[2024-06-27 13:46:48 -0400] [1204842] [ERROR] Worker (pid:1204865) was sent SIGTERM!
[2024-06-27 13:46:48 -0400] [1204842] [ERROR] Shutting down: Master
[2024-06-27 13:46:48 -0400] [1204842] [ERROR] Reason: Worker failed to boot.
